### ISSUE TITLE
 unlink

### ISSUE THREAD

**Issue by bouba89** [MalaGaM/TCL-Clara-Service#1]
lors d'une commandes !cmds le bot unlink

**Comment by ZarTek-Creole** [comment]
Intéressant, je n'ai pas ce problème:
```
[27-03/11:21] * eva.info sets mode: +o ClaraServ
[27-03/11:22] <@MalaGaM> !cmds
[27-03/11:22] <@ClaraServ> Commandes :  !cmds par MalaGaM  
```
Pourriez vous me donnez plus d'informations, en me précisant le IRCD utiliser et sa versions ? Ainsi que la version de votre eggdrop/tcl ? 

Pouvez-vous activer le 'mode debug socket'
`set config(uplink_debug)		1 `

ensuite démarrer votre eggdrop avec les commutateurs '-mt'
`./eggdrop -mt eggdrop.conf`

Executer la commande !cmds et fournir le logs du debug socket lors de l'execution de !cmds, s'il vous plaut

**Comment by bouba89** [comment]
l'ircd est un UnrealIRCd-5.0.8 la version de l'eggdrop est un 1.8.4

**Comment by bouba89** [comment]
./eggdrop -mt gaia.conf

Eggdrop v1.8.4 (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
ERROR: The -n flag is required when using the -c or -t flags. Exiting...

**Comment by bouba89** [comment]
```
11:46:14] Erreur tcl [ClaraServ::Socket:Event]: can't read "database": no such variable
[11:46:14] ClaraServ (services@ClaraServ.Tchat-Radio.com) returned to #accueil.
[11:46:14] #accueil: mode change '+o ClaraServ' by ClaraServ.Tchat-Radio.com
can't read "database": no such variable
    while executing
"llength $database"
    (procedure "ClaraServ::FCT::DB:CMD:LIST" line 3)
    invoked from within
"ClaraServ::FCT::DB:CMD:LIST"
    ("PRIVMSG" arm line 45)
    invoked from within
"switch -exact [lindex $arg 1] {
                "PRIVMSG" {
                        #[23:35:52] cmd(!7up) chan(!7up) user(MalaGaM) pseudo()

                        set sender              [string trim [lindex "$arg" 0..."
    (procedure "ClaraServ::Socket:Event" line 27)
    invoked from within
"ClaraServ::Socket:Event $_n $_a"
[11:46:14] ClaraServ (services@ClaraServ.Tchat-Radio.com) got netsplit.
```

**Comment by ZarTek-Creole** [comment]
Un oublie de ma part, le dossier db/ été manquant ainsi que le fichier database.fr.db dans celui-ci. 
Correction effectuer, retélécharger le repo, ou le zip:
https://github.com/MalaGaM/TCL-Clara-Service/archive/refs/tags/v1.1-beta.zip

extraire le `db/database.fr.db` dans le répertoire ClaraServ

**Comment by bouba89** [comment]
```
[12:11:41] Erreur tcl [ClaraServ::Socket:Event]: couldn't open "/home/bouba89/Bots/Gaia/scripts/Clara/db//salon.db": no such file or directory
couldn't open "/home/bouba89/Bots/Gaia/scripts/Clara/db//salon.db": no such file or directory
    while executing
"open $fichier(salon) "r""
    (procedure "ClaraServ::Server:Connexion" line 12)
    invoked from within
"ClaraServ::Server:Connexion"
    ("SERVER" arm line 4)
    invoked from within
"switch -exact [lindex "$arg" 0] {
                "PING" {
                        ClaraServ::FCT::Socket:Sent "PONG [lindex $arg 1]"
                }
                "NETINFO" {
                        set config(netinfo)             [lindex $..."
    (procedure "ClaraServ::Socket:Event" line 6)
    invoked from within
"ClaraServ::Socket:Event $_n $_a"

```

**Comment by ZarTek-Creole** [comment]
Correction effectuer, veillez m'excusez pour ses désagréments. remplacer à présent le fichier ClaraServ.tcl par la nouvelle version 
https://raw.githubusercontent.com/MalaGaM/TCL-Clara-Service/main/ClaraServ.tcl

**Comment by bouba89** [comment]
je vous en prie merci cela fonctionne mieux
