### ISSUE TITLE
No-Bug:  [ClaraServ Service - Erreur] NÃ©cessite le package ZCT 0.0.9 (ou s pÃ©rieur) pour fonctionner.

### ISSUE THREAD

**Issue by LTEF** [MalaGaM/TCL-Clara-Service#12]
https://github.com/ZarTek-Creole/TCL-ClaraServ/issues/12#issuecomment-1250164178

**Comment by LTEF** [comment]
pour info je l ai telecharge sa ne fonctionne pas
[02:41:06] * [ClaraServ Service - Erreur] NÃ©cessite le package ZCT 0.0.9 (ou s
pÃ©rieur) pour fonctionner.
Le chargement du script a Ã©tÃ© annulÃ©.
TÃ©lÃ©charger-le sur 'https://github.com/ZarTek-Creole/TCL-ZCT'.

**Comment by ZarTek-Creole** [comment]
> pour info je l ai telecharge sa ne fonctionne pas [02:41:06] * [ClaraServ Service - Erreur] NÃ©cessite le package ZCT 0.0.9 (ou s pÃ©rieur) pour fonctionner. Le chargement du script a Ã©tÃ© annulÃ©. TÃ©lÃ©charger-le sur 'https://github.com/ZarTek-Creole/TCL-ZCT'.

Télécharger https://github.com/ZarTek-Creole/TCL-ZCT car ClaraServ Service nécessite le package ZCT 0.0.9 pour fonctionner
